# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

warnings_are_errors: false

addons:
  apt:
    packages:
      - libv8-dev
      - libcurl4-openssl-dev
      - libxml2-dev

matrix:
  include:
  - r: 3.2
  - r: 3.3
  - r: 3.4
  - r: 3.5
  - r: oldrel
  - r: release
    r_packages:
      - covr
      - pkgdown
    after_success:
      - Rscript -e 'covr::codecov()'
      - R CMD INSTALL .
      - Rscript -e 'pkgdown::build_site()'
    deploy:
      - provider: pages
        skip-cleanup: true
        github-token: $GITHUB_PAT
        keep-history: true
        local-dir: docs
        on:
          branch: master
